server:
  port: 9004

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: alyqi:8848  #nacos地址

management:
  endpoints:
    web:
      exposure:
        include: "*"