server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/**,/payment/lb/**

#        - id: payment_routh   #路由的ID 没有固定规则但要求唯一 建议配合服务名
#            uri: http://localhost:8001   #匹配后提供服务的路由地址 同一个路经只需要一个route
#            uri: lb://cloud-payment-service   #匹配注册中心提供的路由地址
#            predicates:
#              - Path=/payment/get/**,/payment/lb/**   #断言，路经相匹配的进行路由
#              - After=2022-12-9T14:15:00.000+08:00[Asia/shanghai]  #在这个时间之后有效
#              - Before=2022-12-9T14:15:00.000+08:00[Asia/shanghai]  #在这个时间之前有效
#              - Between=2022-12-9T14:15:00.000+08:00[Asia/shanghai],2022-12-9T14:15:00.000+08:00[Asia/shanghai]   #在这个时间之间有效
#              - Cookie=cookieName(cookie名字),xxx(正则表达)    #cookie叫cookieName是否存在 --cookie "cookieName=xxx"
#              - Header=headerName(Header名字),xxx(正则表达\d+)    #header叫headerName是否存在 -H "headerName:xxx"

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka