server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: alyqi:8848 #Nacos服务注册地址
    sentinel:
      transport:
        dashboard: alyqi:8858  #配置sentinel dashboard地址
        port: 8719  #默认8719端口，假如被占用会自动从8719开始依次+1扫描，直至找到没有被占用的端口
        clientIp: localhost

management:
  endpoints:
    web:
      exposure:
        include: "*"